name: add new item to project

on:
  issue:
    type: [opened]

jobs:
  automated-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: profile's backlog
          column: 🆕 New
          repo-token: ${{ secrets.FJC_PROFILE_TOKEN }}